inherit_mode:
  merge:
    - Include

AllCops:
  Exclude:
    - vendor/**/*
  Include:
    - .buildkite/danger/**/*
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - fastlane/Fastfile

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 180

Naming/VariableNumber:
  Exclude:
    - fastlane/Fastfile

Naming/FileName:
  Exclude:
    - .buildkite/danger/Dangerfile
