# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.13.0

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "detekt"
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintJalapenoDebug
    plugins: *common_plugins
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Dependency Tree Diff"
    command: |
      cp gradle.properties-example gradle.properties
      .buildkite/commands/dependency-tree-diff.sh
    if: build.pull_request.id != null
    plugins: *common_plugins

  - label: "Unit tests"
    command: |
      echo "--- 🧪 Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew testJalapenoDebug lib:cardreader:testDebug lib:iap:testDebug
      echo "--- ⚒️ Generating and uploading code coverage"
      ./gradlew jacocoTestReport
      .buildkite/commands/upload-code-coverage.sh
    plugins: *common_plugins
    artifact_paths:
      - "**/build/test-results/*/*.xml"

  - label: "Instrumented tests"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems
      echo "--- :closed_lock_with_key: Installing Secrets"
      bundle exec fastlane run configure_apply
      echo "--- 🧪 Testing"
      bundle exec fastlane build_and_instrumented_test
    plugins: *common_plugins
    artifact_paths:
      - "**/build/instrumented-tests/**/*"

  - label: "Ensure Screenshot Tests Build"
    command: |
      echo "--- ⚒️ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleJalapenoDebugAndroidTest
    plugins: *common_plugins

  - label: "🛠 Installable Build"
    command: ".buildkite/commands/installable-build.sh"
    if: build.pull_request.id != null
    plugins: *common_plugins
